services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quotes_user
      POSTGRES_PASSWORD: quotes_pass
      POSTGRES_DB: quotes_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: {}